build:
  version: "{cipher}bb23cc21dc3f82f90916d6570a10de9d04071ef05f56483d5e33e8584008eb2b"

server:
  port: 8083

spring:
  application:
    name: inventory
  profiles:
    active: default
    
eureka:
  instance:
    prefer-ip-address: true 
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_CLIENT_SERVICEURL_DEFAULT_ZONE:http://localhost:8070/eureka/}"