server:
  port: 8073

spring:
  application:
    name: gatewayserver
  config:
    import: "${SPRING_CONFIG_IMPORT}"

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 5s

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - refresh