server:
  port: 8070
spring:
  application:
    name: eurekaserver
  config:
    import: ${SPRING_CONFIG_IMPORT}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true


