server:
  port: 8083

spring:
  application:
    name: inventory
  config:
    import: ${SPRING_CONFIG_IMPORT}
  datasource:
    url: jdbc:h2:mem:inventorydb
    username: sa
    password: sc
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true


