spring:
  application:
    name: products
  config:
    import: ${SPRING_CONFIG_IMPORT}

  datasource:
    url: jdbc:h2:mem:productsdb
    username: sa
    password: sc
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
