spring:
  application:
    name: accounts
  config:
    import: ${SPRING_CONFIG_IMPORT}

  datasource:
    url: jdbc:h2:mem:accountsdb
    username: sc
    password: sc
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

#  sql:
#    init:
#      mode: always

#  h2:
#    console:
#      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    root: info
  file:
    name: logs/app.log