spring:
  application:
    name: accounts
  config:
    import: ${SPRING_CONFIG_IMPORT}

  datasource:
    url: jdbc:h2:mem:accountsdb
    username: sa
    password: sc
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true


logging:
  level:
    root: info
  file:
    name: logs/app.log