server:
  port: 8071

spring:
  application:
    name: configserver

  cloud:
    config:
      server:
        git:
          uri: "git@github.com:juandavyc/spring-boot-3-ms-faketemu.git"
          default-label: configs
          clone-on-start: true
          ignore-local-ssh-settings: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - actuator
          - encrypt
          - decrypt
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

encrypt:
  key: ${ENCRYPT_KEY}


logging:
  level:
    root: info
  file:
    name: logs/app.log
